MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        #NAME: 'improved'
        NAME: 'given_model'
       
        PRETRAINED: True
        #OUT_CHANNELS: [128, 128, 256, 128, 128, 64, 64]
        
        #OUT_CHANNELS: [128, 256, 512, 512] # resnet18
        #OUT_CHANNELS: [128, 256, 512, 128, 128, 128] #resnet34
        #OUT_CHANNELS: [128, 256, 512, 512, 256, 256] #Increased depth of channels
        #OUT_CHANNELS: [512, 1024, 2048, 2048, 1024, 512] # resnet 50
        #OUT_CHANNELS: [128, 256, 512, 512, 256, 256] # resnet 34 sophia
        OUT_CHANNELS: [256,512,256,256,128,128, 64] # resnet 34 given

        #Try different OUT_CHANNELS ?
        
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [320, 240]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [30000, 50000] #Decay: adjust LR
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 0.01 #Maybe a little bit too high?
OUTPUT_DIR: 'outputs/maxpool_error'
DATASET_DIR: "datasets"