MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        #NAME: 'basic'
        NAME: 'given_model'

        PRETRAINED: True
        #PRETRAINED: False
        #OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        OUT_CHANNELS: [256,512,256,256,128,128, 64] # resnet 34 given
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [320, 240]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 100000
    LR_STEPS: [65000, 80000]
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 0.01
OUTPUT_DIR: 'outputs/given_model_cganged_LR_Steps'
DATASET_DIR: "datasets"
