MODEL:
    NUM_CLASSES: 5
    BACKBONE:
<<<<<<< HEAD
        NAME: 'basic'
        #NAME: 'vgg'
        PRETRAINED: False
        #OUT_CHANNELS: [128, 128, 256, 128, 128, 64, 64]
        #OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        OUT_CHANNELS: [128, 256, 512, 256, 128, 64]
=======
        NAME: 'improved'
        PRETRAINED: True
        OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
>>>>>>> d6475f7fe3e6a0fdc214dfd7a64c7d60d547a033
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [320, 240]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
<<<<<<< HEAD
    BATCH_SIZE: 32
    LR: 3e-3
OUTPUT_DIR: 'outputs/basic'
=======
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/improved'
>>>>>>> d6475f7fe3e6a0fdc214dfd7a64c7d60d547a033
DATASET_DIR: "datasets"